name: CS2 RSS → Discord
permissions:
  contents: write
on:
  schedule:
    - cron: "* * * * *"  # 每分钟检查一次
  workflow_dispatch: {}

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      # 1️⃣ 拉取代码
      - uses: actions/checkout@v4

      # 2️⃣ 安装 Node
      - uses: actions/setup-node@v4
        with:
          node-version: "18"

      # 3️⃣ 下载上一次的 .state.json artifact（如果存在）
      - name: Download previous state
        uses: actions/download-artifact@v4
        with:
          name: cs2-rss-state
          path: ./

      # 4️⃣ 安装依赖
      - run: npm install
